{"name": "test_not_existing_user_login", "status": "passed", "description": "Проверяем, что нельзя залогиниться несуществующим юзером", "start": 1730190189374, "stop": 1730190189724, "uuid": "22ee5e64-02a1-40d8-b528-978453bad26b", "historyId": "7f014279b4a83b1fc0d8314ae2b228cc", "testCaseId": "7f014279b4a83b1fc0d8314ae2b228cc", "fullName": "tests.test_courier_login.TestLoginCourier#test_not_existing_user_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "komp"}, {"name": "thread", "value": "2944-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}